class Config {

    static applicationId = 'com.tongsr.courage'
    static appName = 'Courage'

    static compileSdkVersion = 32
    static minSdkVersion = 26
    static targetSdkVersion = 32
    static versionCode = 1_000_000
    static versionName = '1.0.0'

    static routerVersion = "1.1.2"
    static retrofitVersion = "2.9.0"
    static coroutinesVersion = "1.6.4"
    static androidxVersion = "2.5.1"
    static navVersion = "2.5.3"
    static roomVersion = "2.5.0"

    // TODO 项目 sdk 地址管理
    static depConfig = [
            /*Never delete this line*/
            /*Generated by "config.json"*/
            feature_launcher_app       : new DepConfig(true , true , ":feature:launcher:app"),
            feature_wanapp_app         : new DepConfig(true , true , ":feature:wanapp:app"),
            feature_wanapp_pkg         : new DepConfig(true , true , ":feature:wanapp:pkg"),
            feature_wanapp_export      : new DepConfig(true , true , ":feature:wanapp:export"),
            feature_test_pkg           : new DepConfig(true , true , ":feature:test:pkg"),
            feature_test_export        : new DepConfig(true , true , ":feature:test:export"),
            lib_core                   : new DepConfig(true , true , ":lib:core"),
            lib_data                   : new DepConfig(true , true , ":lib:data"),
            lib_router                 : new DepConfig(true , true , ":lib:router"),
            /*Never delete this line*/
            androidxCore            : new DepConfig("androidx.core:core-ktx:1.8.0"),
            activityKtx             : new DepConfig("androidx.activity:activity-ktx:1.5.1"),
            fragmentKtx             : new DepConfig("androidx.fragment:fragment-ktx:1.5.4"),
            lifecycleRuntimeKtx     : new DepConfig("androidx.lifecycle:lifecycle-runtime-ktx:$androidxVersion"),
            lifecycleViewModelKtx   : new DepConfig("androidx.lifecycle:lifecycle-viewmodel-ktx:$androidxVersion"),
            lifecycleLivedataKtx    : new DepConfig("androidx.lifecycle:lifecycle-livedata-ktx:$androidxVersion"),
            lifecycleLivedataCodeKtx: new DepConfig("androidx.lifecycle:lifecycle-livedata-core-ktx:$androidxVersion"),
            androidxAppcompat       : new DepConfig("androidx.appcompat:appcompat:1.4.2"),
            androidxMaterial        : new DepConfig("com.google.android.material:material:1.6.1"), // material风格UI
            constraintLayout        : new DepConfig("androidx.constraintlayout:constraintlayout:2.1.4"),
            routerApi               : new DepConfig("cn.therouter:router:$routerVersion"), // 路由框架
            routerCompiler          : new DepConfig("cn.therouter:apt:$routerVersion"),
            retrofit                : new DepConfig("com.squareup.retrofit2:retrofit:$retrofitVersion"), // 网络
            loggingInterceptor      : new DepConfig("com.squareup.okhttp3:logging-interceptor:4.9.1"),
            retrofitConverter       : new DepConfig("com.squareup.retrofit2:converter-gson:$retrofitVersion"),
            startup                 : new DepConfig("androidx.startup:startup-runtime:1.1.1"), // 启动框架。TheRouter有类似的功能
            datastore               : new DepConfig("androidx.datastore:datastore-preferences:1.0.0"), // 存储数据
            paging3                 : new DepConfig("androidx.paging:paging-runtime:3.1.1"), // 分页
            paging3ktx              : new DepConfig("androidx.paging:paging-runtime-ktx:3.1.1"),
            navigation              : new DepConfig("androidx.navigation:navigation-fragment-ktx:$navVersion"), // 导航栏
            navigationKtx           : new DepConfig("androidx.navigation:navigation-ui-ktx:$navVersion"),
            recyclerview            : new DepConfig("androidx.recyclerview:recyclerview:1.2.1"), // 有ConcatAdapter
            coil                    : new DepConfig("io.coil-kt:coil:2.2.2"), // 图片加载
            glide                   : new DepConfig("com.github.bumptech.glide:glide:4.14.2"), // 图片加载
            glideCompiler           : new DepConfig("com.github.bumptech.glide:compiler:4.14.2"), // 图片加载
            coreCoroutines          : new DepConfig("org.jetbrains.kotlinx:kotlinx-coroutines-core:$coroutinesVersion"), // 协程
            androidCoroutines       : new DepConfig("org.jetbrains.kotlinx:kotlinx-coroutines-android:$coroutinesVersion"),
            gson                    : new DepConfig("com.google.code.gson:gson:2.10"),
            utils                   : new DepConfig("com.blankj:utilcodex:1.31.1"), // 工具集
            viewBindingUtils        : new DepConfig("com.github.kirich1409:viewbindingpropertydelegate-noreflection:1.5.6"), // 委托方式实现ViewBinding
            timber                  : new DepConfig("com.jakewharton.timber:timber:5.0.1"), // 用于线上的日志
            tabLayout               : new DepConfig("com.github.angcyo.DslTablayout:TabLayout:3.5.3"), // Tab
            brvah                   : new DepConfig("io.github.cymchad:BaseRecyclerViewAdapterHelper:4.0.0-beta04"), // RecyclerView
            room                    : new DepConfig("androidx.room:room-runtime:$roomVersion"), // 数据库
            roomCompiler            : new DepConfig("androidx.room:room-compiler:$roomVersion"),
            roomKtx                 : new DepConfig("androidx.room:room-ktx:$roomVersion"),
            roomPaging              : new DepConfig("androidx.room:room-paging:$roomVersion"),
            leakcanary              : new DepConfig("com.squareup.leakcanary:leakcanary-android:2.10"), // leakcanary;debugImplementation引用
    ]

}